# Generated by Django 4.2 on 2024-07-26 01:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.TextField(verbose_name='Details')),
                ('rating', models.PositiveSmallIntegerField(verbose_name='Rate (1-5)')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.person', verbose_name='Person')),
            ],
        ),
    ]
