# Generated by Django 4.2 on 2024-07-31 02:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cv', models.FileField(upload_to='cv', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['docx'])])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
