# Generated by Django 4.2 on 2024-07-31 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_name', models.CharField(choices=[('Lunes', 'Lunes'), ('Martes', 'Martes'), ('Miércoles', 'Miércoles'), ('Jueves', 'Jueves'), ('Viernes', 'Viernes'), ('Sábado', 'Sábado'), ('Domingo', 'Domingo')], max_length=100, verbose_name='Day (name)')),
                ('enterprise', models.CharField(choices=[('Grupo LATAM', 'Grupo LATAM'), ('Sky Airline', 'Sky Airline'), ('Aerolineas Argentinas', 'Aerolineas Argentinas'), ('Copa Air', 'Copa Air'), ('Latin American Wings', 'Latin American Wings'), ('Avianca', 'Avianca'), ('Gol Trans', 'Gol Trans'), ('American Airlines', 'American Airlines'), ('Air Canada', 'Air Canada'), ('Delta Air', 'Delta Air'), ('Iberia', 'Iberia'), ('Air France', 'Air France'), ('Aeromexico', 'Aeromexico'), ('JetSmart SPA', 'JetSmart SPA'), ('United Airlines', 'United Airlines'), ('Alitalia', 'Alitalia'), ('K.L.M.', 'K.L.M.'), ('British Airways', 'British Airways'), ('Qantas Airways', 'Qantas Airways'), ('Oceanair Linhas Aereas', 'Oceanair Linhas Aereas'), ('Austral', 'Austral'), ('Plus Ultra Lineas Aereas', 'Plus Ultra Lineas Aereas'), ('Lacsa', 'Lacsa')], max_length=100, verbose_name='Enterprise')),
                ('month_name', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12')], max_length=100, verbose_name='Month')),
                ('date_to_search', models.DateTimeField(verbose_name='Date')),
                ('prediction', models.BooleanField(blank=True, null=True, verbose_name='has delay')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
